@baseUrl = http://localhost:8080/api/auth

### Registrar Usuário
# Cria um novo usuário com papel COMPANY (ou CANDIDATE)
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "Gabriel",
    "email": "gabriel@example.com",
    "password": "password123",
    "role": "COMPANY"
}

### Login
# Realiza o login e retorna o Access Token
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "gabrielmartins@hotmail.com",
    "password": "c4ndidate"
}
